apiVersion: batch/v1
kind: CronJob
metadata:
  name: secsync-cronjob
  namespace: app
spec:
  schedule: "0 * * * *"  # 每小时运行一次
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: secsync-sa
          containers:
          - name: sync-secrets
            image: ghcr.io/bboysoulcn/secsync:latest
            env:
            - name: SOURCE_NAMESPACE
              value: "source-namespace"
            - name: TARGET_NAMESPACES
              value: "target-namespace1,target-namespace2,target-namespace3"
            - name: SECRET_NAME
              value: "secret-name"
          restartPolicy: Never
      backoffLimit: 4
